DROP DATABASE IF EXISTS HOSPITAL;
 
 
CREATE DATABASE HOSPITAL;
 
USE HOSPITAL;
 
CREATE TABLE VIRUS(
ID INT AUTO_INCREMENT,
NOME VARCHAR(45),
NOME_CIENTIFICO VARCHAR(50),
DESCRICAO TEXT,
PRIMARY KEY(ID)
);
 
INSERT INTO VIRUS VALUES(NULL, "Coxsackievirus","Coxsackie","Virus Coxsackie é parte da familia dos enterovirus.");
INSERT INTO VIRUS VALUES(NULL, "Mokola","Virus da raiva","Virus da raiva é um virus que ataca animais e humanos.");
INSERT INTO VIRUS VALUES(NUll, "")






CREATE TABLE VIROSE(
ID INT AUTO_INCREMENT,
NOME VARCHAR(50),
DESCRICAO TEXT,
VIRUS_ID INT,
PRIMARY KEY(ID),
CONSTRAINT VIROSE_VIRUS FOREIGN KEY (VIRUS_ID) REFERENCES VIRUS(ID)
);
 
INSERT INTO VIROSE VALUES(NULL, "Epatite A","Virus pode causar Epatite A.",1 );
INSERT INTO VIROSE VALUES(NULL, "Raiva","Pode matar o animal e o humano.",2 );
 
CREATE TABLE INSTITUICAO(
ID INT AUTO_INCREMENT,
NOME VARCHAR(60),
ENDERECO VARCHAR(100),
PRIMARY KEY(ID)
);
 
INSERT INTO INSTITUICAO VALUES(NULL, "Instuto toto","rua das lontras 1025");
  
CREATE TABLE JORNAL(
ID INT AUTO_INCREMENT,
NOME VARCHAR(60),
N_VOLUME INT,
N_EDICAO INT,
PRIMARY KEY(ID)
);
 
INSERT INTO JORNAL VALUES (NULL,"Daile Virus",5,6);
 
CREATE TABLE MEDICOS(
ID INT AUTO_INCREMENT,
NOME VARCHAR(50),
PRIMARY KEY(ID)
);
 
INSERT INTO MEDICOS VALUES(NULL, "Dr. Paupito Pomposo");
 
CREATE TABLE PUBLICACAO(
ID INT AUTO_INCREMENT,
TITULO VARCHAR(60),
RESUMO TEXT,
ABSTRACT TEXT,
N_CONTRATO INT,
DATA_INICIO DATE,
DATA_EDICAO DATE,
JORNAL_ID INT,
VALOR DOUBLE,
PRIMARY KEY (ID),
CONSTRAINT JORNAL_PUBLICACAO FOREIGN KEY (JORNAL_ID) REFERENCES JORNAL(ID)
);
 
INSERT INTO PUBLICACAO VALUES(NULL,"Virus","Virus varios tipos e perigosos.","dfaf",12,2015-12-11,2016-12-6,1,3.23);
 
 
CREATE TABLE AUTOR(
PUBLICACAO_ID INT,
MEDICOS_ID INT,
PRIMARY KEY(PUBLICACAO_ID, MEDICOs_ID),
CONSTRAINT PUBLICACAO_MEDICOS FOREIGN KEY (PUBLICACAO_ID) REFERENCES PUBLICACAO(ID),
CONSTRAINT PUBLICACAO_MEDICOS1 FOREIGN KEY (MEDICOS_ID) REFERENCES MEDICOS(ID) 
);
 
 
 
CREATE TABLE INSTITUICAO_PUBLICACAO(
PUBLICACAO_ID INT,
INSTITUICAO_ID INT,
PRIMARY KEY(PUBLICACAO_ID, INSTITUICAO_ID),
CONSTRAINT PUBLICACAO_PUBLICACAO FOREIGN KEY (PUBLICACAO_ID) REFERENCES PUBLICACAO(ID),
CONSTRAINT PUBLICACAO_PUBLICACAO1 FOREIGN KEY (INSTITUICAO_ID) REFERENCES INSTITUICAO(ID)
);
 
 
CREATE TABLE VIROSE_PUBLICACAO(
PUBLICACAO_ID INT,
VIROSE_ID INT,
PRIMARY KEY(PUBLICACAO_ID,VIROSE_ID),
CONSTRAINT PUBLICACAO_VIROSE FOREIGN KEY (PUBLICACAO_ID) REFERENCES PUBLICACAO(ID),
CONSTRAINT PUBLICACAO_VIROSE1 FOREIGN KEY (VIROSE_ID) REFERENCES VIROSE(ID)
);
 
 
 
CREATE TABLE PUBLICA_PUBLICACAO(
PUBLICACAO_ID INT NOT NULL,
PUBLICACAO_ID1 INT NOT NULL,
PRIMARY KEY(PUBLICACAO_ID, PUBLICACAO_ID1),
CONSTRAINT PUBLICA_PUBLICA FOREIGN KEY (PUBLICACAO_ID) REFERENCES PUBLICACAO(ID),
CONSTRAINT PUBLICA_PUBLICA1 FOREIGN KEY (PUBLICACAO_ID1) REFERENCES PUBLICACAO(ID)
);
 
 
SHOW TABLES;
 
SELECT * FROM VIRUS;
 
SELECT * FROM VIROSE;
 
SELECT VIRUS.NOME, VIRUS.NOME_CIENTIFICO, VIROSE.NOME, VIROSE.DESCRICAO FROM VIROSE
INNER JOIN VIRUS ON VIROSE.ID = VIRUS.ID;
 
SELECT INSTITUICAO.NOME, MEDICOS.NOME, PUBLICACAO.TITULO, JORNAL.NOME FROM JORNAL
INNER JOIN INSTITUICAO ON JORNAL.ID = INSTITUICAO.ID 
INNER JOIN MEDICOS ON JORNAL.ID = MEDICOS.ID 
INNER JOIN PUBLICACAO ON JORNAL.ID = PUBLICACAO.ID;

SELECT PUBLICACAO.ID, JORNAL.ID, PUBLICACAO.DATA_INICIO, PUBLICACAO.TITULO, PUBLICACAO.RESUMO FROM 
VIRUS 
INNER JOIN 


